const keywordResponses = [
    { keys: ["Genesis chapter 1"], response: {
        1: "In the beginning God created the heavens and the earth.",
        2: "Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters.",
        3: "And God said, 'Let there be light,' and there was light.",
        4: "God saw that the light was good, and he separated the light from the darkness.",
        5: "God called the light 'day,' and the darkness he called 'night.' And there was evening, and there was morning—the first day.",
        6: "And God said, 'Let there be a vault between the waters to separate water from water.'",
        7: "So God made the vault and separated the water under the vault from the water above it. And it was so.",
        8: "God called the vault 'sky.' And there was evening, and there was morning—the second day.",
        9: "And God said, 'Let the water under the sky be gathered to one place, and let dry ground appear.' And it was so.",
        10: "God called the dry ground 'land,' and the gathered waters he called 'seas.' And God saw that it was good.",
        11: "Then God said, 'Let the land produce vegetation: seed-bearing plants and trees on the land that bear fruit with seed in it, according to their various kinds.' And it was so.",
        12: "The land produced vegetation: plants bearing seed according to their kinds and trees bearing fruit with seed in it according to their kinds. And God saw that it was good.",
        13: "And there was evening, and there was morning—the third day.",
        14: "And God said, 'Let there be lights in the vault of the sky to separate the day from the night, and let them serve as signs to mark sacred times, and days and years,",
        15: "and let them be lights in the vault of the sky to give light on the earth.' And it was so.",
        16: "God made two great lights—the greater light to govern the day and the lesser light to govern the night. He also made the stars.",
        17: "God set them in the vault of the sky to give light on the earth,",
        18: "to govern the day and the night, and to separate light from darkness. And God saw that it was good.",
        19: "And there was evening, and there was morning—the fourth day.",
        20: "And God said, 'Let the water teem with living creatures, and let birds fly above the earth across the vault of the sky.'",
        21: "So God created the great creatures of the sea and every living thing with which the water teems, and that moves about in it, according to their kinds, and every winged bird according to its kind. And God saw that it was good.",
        22: "God blessed them and said, 'Be fruitful and increase in number and fill the water in the seas, and let the birds increase on the earth.'",
        23: "And there was evening, and there was morning—the fifth day.",
        24: "And God said, 'Let the land produce living creatures according to their kinds: the livestock, the creatures that move along the ground, and the wild animals, each according to its kind.' And it was so.",
        25: "God made the wild animals according to their kinds, the livestock according to their kinds, and all the creatures that move along the ground according to their kinds. And God saw that it was good.",
        26: "Then God said, 'Let us make mankind in our image, in our likeness, so that they may rule over the fish in the sea and the birds in the sky, over the livestock and all the wild animals, and over all the creatures that move along the ground.'",
        27: "So God created mankind in his own image, in the image of God he created them; male and female he created them.",
        28: "God blessed them and said to them, 'Be fruitful and increase in number; fill the earth and subdue it. Rule over the fish in the sea and the birds in the sky and over every living creature that moves on the ground.'",
        29: "Then God said, 'I give you every seed-bearing plant on the face of the whole earth and every tree that has fruit with seed in it. They will be yours for food.'",
        30: "And to all the beasts of the earth and all the birds in the sky and all the creatures that move on the ground—everything that has the breath of life in it—I give every green plant for food.' And it was so.",
        31: "God saw all that he had made, and it was very good. And there was evening, and there was morning—the sixth day."
    }},
    { keys: ["Genesis chapter 2"], response: {
        1: "Thus the heavens and the earth were completed in all their vast array.",
        2: "By the seventh day God had finished the work he had been doing; so on the seventh day he rested from all his work.",
        3: "Then God blessed the seventh day and made it holy, because on it he rested from all the work of creating that he had done.",
        4: "This is the account of the heavens and the earth when they were created, when the Lord God made the earth and the heavens.",
        5: "Now no shrub had yet appeared on the earth and no plant had yet sprung up, for the Lord God had not sent rain on the earth and there was no one to work the ground,",
        6: "but streams came up from the earth and watered the whole surface of the ground.",
        7: "Then the Lord God formed a man from the dust of the ground and breathed into his nostrils the breath of life, and the man became a living being.",
        8: "Now the Lord God had planted a garden in the east, in Eden; and there he put the man he had formed.",
        9: "The Lord God made all kinds of trees grow out of the ground—trees that were pleasing to the eye and good for food. In the middle of the garden were the tree of life and the tree of the knowledge of good and evil.",
        10: "A river watering the garden flowed from Eden; from there it was separated into four headwaters.",
        11: "The name of the first is the Pishon; it winds through the entire land of Havilah, where there is gold.",
        12: "The gold of that land is good; aromatic resin and onyx are also there.",
        13: "The name of the second river is the Gihon; it winds through the entire land of Cush.",
        14: "The name of the third river is the Tigris; it runs along the east side of Asshur. And the fourth river is the Euphrates.",
        15: "The Lord God took the man and put him in the Garden of Eden to work it and take care of it.",
        16: "And the Lord God commanded the man, 'You are free to eat from any tree in the garden; but you must not eat from the tree of the knowledge of good and evil, for when you eat from it you will certainly die.'",
        17: "The Lord God said, 'It is not good for the man to be alone. I will make a helper suitable for him.'",
        18: "Now the Lord God had formed out of the ground all the wild animals and all the birds in the sky. He brought them to the man to see what he would name them; and whatever the man called each living creature, that was its name.",
        19: "So the man gave names to all the livestock, the birds in the sky and all the wild animals. But for Adam no suitable helper was found.",
        20: "So the Lord God caused the man to fall into a deep sleep; and while he was sleeping, he took one of the man’s ribs and then closed up the place with flesh.",
        21: "Then the Lord God made a woman from the rib he had taken out of the man, and he brought her to the man.",
        22: "The man said, 'This is now bone of my bones and flesh of my flesh; she shall be called 'woman,' for she was taken out of man.'",
        23: "That is why a man leaves his father and mother and is united to his wife, and they become one flesh.",
        24: "Adam and his wife were both naked, and they felt no shame."
    }},
    { keys: ["Genesis chapter 3"], response: {
        1: "Now the serpent was more crafty than any of the wild animals the Lord God had made. He said to the woman, 'Did God really say, “You must not eat from any tree in the garden?”'",
        2: "The woman said to the serpent, 'We may eat fruit from the trees in the garden,",
        3: "but God said, “You must not eat fruit from the tree that is in the middle of the garden, and you must not touch it, or you will die.”'",
        4: "'You will not certainly die,' the serpent said to the woman.",
        5: "'For God knows that when you eat from it your eyes will be opened, and you will be like God, knowing good and evil.'",
        6: "When the woman saw that the fruit of the tree was good for food and pleasing to the eye, and also desirable for gaining wisdom, she took some and ate it. She also gave some to her husband, who was with her, and he ate it.",
        7: "Then the eyes of both of them were opened, and they realized they were naked; so they sewed fig leaves together and made themselves loincloths.",
        8: "Then the man and his wife heard the sound of the Lord God as he was walking in the garden in the cool of the day, and they hid from the Lord God among the trees of the garden.",
        9: "But the Lord God called to the man, 'Where are you?'",
        10: "He answered, 'I heard you in the garden, and I was afraid because I was naked; so I hid.'",
        11: "'Who told you that you were naked? Have you eaten from the tree that I commanded you not to eat from?'",
        12: "The man said, 'The woman you put here with me—she gave me some fruit from the tree, and I ate it.'",
        13: "Then the Lord God said to the woman, 'What is this you have done?'",
        14: "The Lord God said to the serpent, 'Because you have done this, cursed are you above all livestock and all wild animals! You will crawl on your belly and you will eat dust all the days of your life.'",
        15: "'And I will put enmity between you and the woman, and between your offspring and hers; he will crush your head, and you will strike his heel.'",
        16: "To the woman he said, 'I will make your pains in childbearing very severe; with painful labor you will give birth to children. Your desire will be for your husband, and he will rule over you.'",
        17: "To Adam he said, 'Because you listened to your wife and ate fruit from the tree about which I commanded you, “You must not eat from it,” cursed is the ground because of you; through painful toil you will eat food from it all the days of your life.'",
        18: "'It will produce thorns and thistles for you, and you will eat the plants of the field.'",
        19: "By the sweat of your brow you will eat your food until you return to the ground, since from it you were taken; for dust you are and to dust you will return.'",
        20: "Adam named his wife Eve, because she would become the mother of all the living.",
        21: "The Lord God made garments of skin for Adam and his wife and clothed them.",
        22: "And the Lord God said, 'The man has now become like one of us, knowing good and evil. He must not be allowed to reach out his hand and take also from the tree of life and eat, and live forever.'",
        23: "So the Lord God banished him from the Garden of Eden to work the ground from which he had been taken.",
        24: "After he drove the man out, he placed on the east side of the Garden of Eden cherubim and a flaming sword flashing back and forth to guard the way to the tree of life."
    }},
    {
        "keys": ["Genesis chapter 4"],
        "response": {
            1: "Adam made love to his wife Eve, and she became pregnant and gave birth to Cain. She said, 'With the help of the Lord I have brought forth a man.'",
            2: "Later she gave birth to his brother Abel. Now Abel kept flocks, and Cain worked the soil.",
            3: "In the course of time Cain brought some of the fruits of the soil as an offering to the Lord.",
            4: "And Abel also brought an offering—fat portions from some of the firstborn of his flock. The Lord looked with favor on Abel and his offering,",
            5: "but on Cain and his offering he did not look with favor. So Cain was very angry, and his face was downcast.",
            6: "Then the Lord said to Cain, 'Why are you angry? Why is your face downcast?",
            7: "If you do what is right, will you not be accepted? But if you do not do what is right, sin is crouching at your door; it desires to have you, but you must rule over it.'",
            8: "Now Cain said to Abel, 'Let's go out to the field.' And while they were in the field, Cain attacked his brother Abel and killed him.",
            9: "Then the Lord said to Cain, 'Where is your brother Abel?' 'I don't know,' he replied. 'Am I my brother's keeper?'",
            10: "The Lord said, 'What have you done? Listen! Your brother's blood cries out to me from the ground.'",
            11: "Now you are under a curse and driven from the ground, which opened its mouth to receive your brother's blood from your hand.",
            12: "When you work the ground, it will no longer yield good crops for you. You will be a restless wanderer on the earth.'",
            13: "Cain said to the Lord, 'My punishment is more than I can bear.",
            14: "Today you are driving me from the land, and I will be hidden from your presence; I will be a restless wanderer on the earth, and whoever finds me will kill me.'",
            15: "But the Lord said to him, 'Not so; anyone who kills Cain will suffer vengeance seven times over.' Then the Lord put a mark on Cain so that no one who found him would kill him.",
            16: "So Cain went out from the Lord's presence and lived in the land of Nod, east of Eden.",
            17: "Cain made love to his wife, and she became pregnant and gave birth to Enoch. Cain was then building a city, and he named it after his son Enoch.",
            18: "To Enoch was born Irad, and Irad was the father of Mehujael, and Mehujael the father of Methushael, and Methushael the father of Lamech.",
            19: "Lamech married two women, one named Adah and the other Zillah.",
            20: "Adah gave birth to Jabal; he was the father of those who live in tents and raise livestock.",
            21: "His brother's name was Jubal; he was the father of all who play stringed instruments and pipes.",
            22: "Zillah also had a son, Tubal-Cain, who forged all kinds of tools out of bronze and iron. Tubal-Cain's sister was Naamah.",
            23: "Lamech said to his wives, 'Adah and Zillah, listen to me; wives of Lamech, hear my words. I have killed a man for wounding me, a young man for injuring me.",
            24: "If Cain is avenged seven times, then Lamech seventy-seven times.'",
            25: "Adam made love to his wife again, and she gave birth to a son and named him Seth, saying, 'God has granted me another child in place of Abel, since Cain killed him.'",
            26: "Seth also had a son, and he named him Enosh. At that time people began to call on the name of the Lord."
        }
    },
    {
        "keys": ["Genesis chapter 5"],
        "response": {
            1: "This is the written account of Adam's family line. When God created mankind, he made them in the likeness of God.",
            2: "He created them male and female and blessed them. And he named them ‘Mankind’ when they were created.",
            3: "When Adam had lived 130 years, he had a son in his own likeness, in his own image; and he named him Seth.",
            4: "After Seth was born, Adam lived 800 years and had other sons and daughters.",
            5: "Altogether, Adam lived a total of 930 years, and then he died.",
            6: "When Seth had lived 105 years, he became the father of Enosh.",
            7: "And after he became the father of Enosh, Seth lived 807 years and had other sons and daughters.",
            8: "Altogether, Seth lived a total of 912 years, and then he died.",
            9: "When Enosh had lived 90 years, he became the father of Kenan.",
            10: "And after he became the father of Kenan, Enosh lived 815 years and had other sons and daughters.",
            11: "Altogether, Enosh lived a total of 905 years, and then he died.",
            12: "When Kenan had lived 70 years, he became the father of Mahalalel.",
            13: "And after he became the father of Mahalalel, Kenan lived 840 years and had other sons and daughters.",
            14: "Altogether, Kenan lived a total of 910 years, and then he died.",
            15: "When Mahalalel had lived 65 years, he became the father of Jared.",
            16: "And after he became the father of Jared, Mahalalel lived 830 years and had other sons and daughters.",
            17: "Altogether, Mahalalel lived a total of 895 years, and then he died.",
            18: "When Jared had lived 162 years, he became the father of Enoch.",
            19: "And after he became the father of Enoch, Jared lived 800 years and had other sons and daughters.",
            20: "Altogether, Jared lived a total of 962 years, and then he died.",
            21: "When Enoch had lived 65 years, he became the father of Methuselah.",
            22: "And after he became the father of Methuselah, Enoch walked faithfully with God 300 years and had other sons and daughters.",
            23: "Altogether, Enoch lived a total of 365 years.",
            24: "Enoch walked faithfully with God; then he was no more, because God took him away.",
            25: "When Methuselah had lived 187 years, he became the father of Lamech.",
            26: "And after he became the father of Lamech, Methuselah lived 782 years and had other sons and daughters.",
            27: "Altogether, Methuselah lived a total of 969 years, and then he died.",
            28: "When Lamech had lived 182 years, he had a son.",
            29: "He named him Noah and said, 'He will comfort us in the labor and painful toil of our hands caused by the ground the Lord has cursed.'",
            30: "After Noah was born, Lamech lived 595 years and had other sons and daughters.",
            31: "Altogether, Lamech lived a total of 777 years, and then he died.",
            32: "After Noah was 500 years old, he became the father of Shem, Ham and Japheth."
        }
    },
    {
        "keys": ["Genesis chapter 6"],
        "response": {
            1: "When human beings began to increase in number on the earth and daughters were born to them,",
            2: "the sons of God saw that the daughters of humans were beautiful, and they married any of them they chose.",
            3: "Then the Lord said, 'My Spirit will not contend with humans forever, for they are mortal; their days will be a hundred and twenty years.'",
            4: "The Nephilim were on the earth in those days—and also afterward—when the sons of God went to the daughters of humans and had children by them. They were the heroes of old, men of renown.",
            5: "The Lord saw how great the wickedness of the human race had become on the earth, and that every inclination of the thoughts of the human heart was only evil all the time.",
            6: "The Lord regretted that he had made human beings on the earth, and his heart was deeply troubled.",
            7: "So the Lord said, 'I will wipe from the face of the earth the human race I have created—and with them the animals, the birds and the creatures that move along the ground—for I regret that I have made them.'",
            8: "But Noah found favor in the eyes of the Lord.",
            9: "This is the account of Noah and his family. Noah was a righteous man, blameless among the people of his time, and he walked faithfully with God.",
            10: "Noah had three sons: Shem, Ham and Japheth.",
            11: "Now the earth was corrupt in God's sight and was full of violence.",
            12: "God saw how corrupt the earth had become, for all the people on earth had corrupted their ways.",
            13: "So God said to Noah, 'I am going to put an end to all people, for the earth is filled with violence because of them. I am surely going to destroy both them and the earth.'",
            14: "'So make yourself an ark of cypress wood; make rooms in it and coat it with pitch inside and out.'",
            15: "'This is how you are to build it: The ark is to be four hundred fifty feet long, seventy five feet wide and fourty five feet high.'",
            16: "'Make a roof for it, leaving below the roof an opening one foot high all around. Put a door in the side of the ark and make lower, middle and upper decks.'",
            17: "'I am going to bring floodwaters on the earth to destroy all life under the heavens, every creature that has the breath of life in it. Everything on earth will perish.'",
            18: "'But I will establish my covenant with you, and you will enter the ark— you and your sons and your wife and your sons’ wives with you.'",
            19: "'You are to bring into the ark two of all living creatures, male and female, to keep them alive with you.'",
            20: "'Two of every kind of bird, of every kind of animal and of every kind of creature that moves along the ground will come to you to be kept alive.'",
            21: "'You are to take every kind of food that is to be eaten and store it away as food for you and for them.'",
            22: "Noah did everything just as God commanded him."
        }
    },
   {
        "keys": ["Genesis chapter 7"],
        "response": {
            1: "The Lord then said to Noah, “Go into the ark, you and your whole family, because I have found you righteous in this generation.",
            2: "Take with you seven pairs of every kind of clean animal, a male and its mate, and one pair of every kind of unclean animal, a male and its mate,",
            3: "and also seven pairs of every kind of bird, male and female, to keep their various kinds alive throughout the earth. ",
            4: "Seven days from now I will send rain on the earth for forty days and forty nights, and I will wipe from the face of the earth every living creature I have made.”",
            5: "And Noah did all that the Lord commanded him.",
            6: "Noah was six hundred years old when the floodwaters came on the earth.",
            7: "And Noah and his sons and his wife and his sons’ wives entered the ark to escape the waters of the flood.",
            8: "Pairs of clean and unclean animals, of birds and of all creatures that move along the ground,",
            9: "male and female, came to Noah and entered the ark, as God had commanded Noah.",
            10: "And after the seven days the floodwaters came on the earth.",
            11: "In the six hundredth year of Noah’s life, on the seventeenth day of the second month—on that day all the springs of the great deep burst forth, and the floodgates of the heavens were opened.",
            12: "And rain fell on the earth forty days and forty nights.",
            13: "On that very day Noah and his sons, Shem, Ham and Japheth, together with his wife and the wives of his three sons, entered the ark.",
            14: "They had with them every wild animal according to its kind, all livestock according to their kinds, every creature that moves along the ground according to its kind and every bird according to its kind, everything with wings.",
            15: "Pairs of all creatures that have the breath of life in them came to Noah and entered the ark. ",
            16: "The animals going in were male and female of every living thing, as God had commanded Noah. Then the Lord shut him in.",
            17: "For forty days the flood kept coming on the earth, and as the waters increased they lifted the ark high above the earth.",
            18: "The waters rose and increased greatly on the earth, and the ark floated on the surface of the water.",
            19: "They rose greatly on the earth, and all the high mountains under the entire heavens were covered.",
            20: "The waters rose and covered the mountains to a depth of more than fifteen cubits.",
            21: "Every living thing that moved on land perished—birds, livestock, wild animals, all the creatures that swarm over the earth, and all mankind.",
            22: "Everything on dry land that had the breath of life in its nostrils died.",
            23: "Every living thing on the face of the earth was wiped out; people and animals and the creatures that move along the ground and the birds were wiped from the earth. Only Noah was left, and those with him in the ark.",
            24: "The waters flooded the earth for a hundred and fifty days.",
   }
   },
   { "keys": ["Genesis chapter 8"],
    "response":{
        1: " But God remembered Noah and all the wild animals and the livestock that were with him in the ark, and he sent a wind over the earth, and the waters receded." ,
        2: " Now the springs of the deep and the floodgates of the heavens had been closed, and the rain had stopped falling from the sky.",
        3: "The water receded steadily from the earth. At the end of the hundred and fifty days the water had gone down,",
        4: "and on the seventeenth day of the seventh month the ark came to rest on the mountains of Ararat.",
        5: "The waters continued to recede until the tenth month, and on the first day of the tenth month the tops of the mountains became visible.",
        6: "After forty days Noah opened a window he had made in the ark",
        7: "and sent out a raven, and it kept flying back and forth until the water had dried up from the earth.",
        8: "Then he sent out a dove to see if the water had receded from the surface of the ground.",
        9: "But the dove could find nowhere to perch because there was water over all the surface of the earth; so it returned to Noah in the ark. He reached out his hand and took the dove and brought it back to himself in the ark. ",
        10: "He waited seven more days and again sent out the dove from the ark.",
        11: "When the dove returned to him in the evening, there in its beak was a freshly plucked olive leaf! Then Noah knew that the water had receded from the earth.",
        12: "He waited seven more days and sent the dove out again, but this time it did not return to him.",
        13: "By the first day of the first month of Noah’s six hundred and first year, the water had dried up from the earth. Noah then removed the covering from the ark and saw that the surface of the ground was dry.",
        14: "By the twenty-seventh day of the second month the earth was completely dry.",
        15: "Then God said to Noah,",
        16: "'Come out of the ark, you and your wife and your sons and their wives.",
        17: "Bring out every kind of living creature that is with you—the birds, the animals, and all the creatures that move along the ground—so they can multiply on the earth and be fruitful and increase in number on it.'",
        18: "So Noah came out, together with his sons and his wife and his sons’ wives.",
        19: "All the animals and all the creatures that move along the ground and all the birds—everything that moves on land—came out of the ark, one kind after another.",
        20: "Then Noah built an altar to the Lord and, taking some of all the clean animals and clean birds, he sacrificed burnt offerings on it.",
        21: "The Lord smelled the pleasing aroma and said in his heart: “Never again will I curse the ground because of humans, even though[a] every inclination of the human heart is evil from childhood. And never again will I destroy all living creatures, as I have done.",
        22: "As long as the earth endures, seedtime and harvest, cold and heat, summer and winter, day and night will never cease.”",
    }
  },
  {"keys": ["Genesis chapter 9"],
    "response": {
        1: "Then God blessed Noah and his sons, saying to them, 'Be fruitful and increase in number and fill the earth.",
        2: "The fear and dread of you will fall on all the beasts of the earth and on all the birds in the sky, on every creature that moves along the ground and on all the fish in the sea; they are given into your hands.",
        3: "Everything that lives and moves will be food for you. Just as I gave you the green plants, I now give you everything.",
        4: "But you must not eat meat that has its lifeblood still in it.",
        5: "And for your lifeblood I will surely demand an accounting. I will demand an accounting from every animal. And from each human being, too, I will demand an accounting for the life of another human being.",
        6: "'Whoever sheds human blood, by humans shall their blood be shed; for in the image of God has God made mankind.",
        7: "As for you, be fruitful and increase in number; multiply on the earth and increase upon it.'",
        8: "Then God said to Noah and to his sons with him:",
        9: "'I now establish my covenant with you and with your descendants after you",
        10: "'and with every living creature that was with you—the birds, the livestock and all the wild animals—all those that came out of the ark with you—every living creature on earth.",
        11: "'I establish my covenant with you: Never again will all life be destroyed by the waters of a flood; never again will there be a flood to destroy the earth.'",
        12: "'And God said, 'This is the sign of the covenant I am making between me and you and every living creature with you, a covenant for all generations to come:",
        13: "'I have set my rainbow in the clouds, and it will be the sign of the covenant between me and the earth.",
        14: "'Whenever I bring clouds over the earth and the rainbow appears in the clouds,",
        15: "'I will remember my covenant between me and you and all living creatures of every kind. Never again will the waters become a flood to destroy all life.",
        16: "'Whenever the rainbow appears in the clouds, I will see it and remember the everlasting covenant between God and all living creatures of every kind that is on the earth.'",
        17: "'So God said to Noah, 'This is the sign of the covenant I have established between me and all life on the earth.'",
        18: "The sons of Noah who came out of the ark were Shem, Ham and Japheth. (Ham was the father of Canaan.)",
        19: "These were the three sons of Noah, and from them came the people who were scattered over the whole earth.",
        20: "Noah, a man of the soil, proceeded[a] to plant a vineyard. ",
        21: "When he drank some of its wine, he became drunk and lay uncovered inside his tent.",
        22: "Ham, the father of Canaan, saw his father naked and told his two brothers outside.",
        23: "But Shem and Japheth took a garment and laid it across their shoulders; then they walked in backward and covered their father’s naked body. Their faces were turned the other way so that they would not see their father naked.",
        24: "When Noah awoke from his wine and found out what his youngest son had done to him,",
        25: "he said, 'Cursed be Canaan! The lowest of slaves will he be to his brothers.'",
        26: "'He also said, 'Praise be to the Lord, the God of Shem! May Canaan be the slave of Shem.",
        27: "'May God extend Japheth's territory; may Japheth live in the tents of Shem, and may Canaan be the slave of Japheth.'",
        28: "After the flood Noah lived 350 years. 29 Noah lived a total of 950 years, and then he died.",
  }
}
];